DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `DELETE_MESSAGE`(IN `AMESSAGE_ID` INT)
    MODIFIES SQL DATA
DELETE FROM MESSAGES WHERE MESSAGE_ID = AMESSAGE_ID$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_MESSAGE`(IN `AUTILISATEUR_ID` INT, IN `ATITRE` VARCHAR(80), IN `ATEXTE` TEXT)
    MODIFIES SQL DATA
INSERT INTO messages (
    	UTILISATEUR_ID,
    	TITRE,
    	TEXTE)
        VALUES (
            AUTILISATEUR_ID,
            ATITRE,
            ATEXTE)$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UPDATE_MESSAGE`(IN `AMESSAGE_ID` INT, IN `ATITRE` VARCHAR(80), IN `ATEXTE` TEXT)
    MODIFIES SQL DATA
UPDATE MESSAGES SET
	TITRE = ATITRE,
    TEXTE = ATEXTE
WHERE MESSAGE_ID = AMESSAGE_ID$$
DELIMITER ;
