DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `DELETE_MESSAGE`(IN `AMESSAGE_ID` INT)
    MODIFIES SQL DATA
DELETE FROM MESSAGES WHERE MESSAGE_ID = AMESSAGE_ID$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GETDONNEES_UTILISATEUR`(INOUT `AMAIL` VARCHAR(255), IN `AMDP` VARCHAR(255), OUT `AUTILISATEUR_ID` INT, OUT `ASURNOM` CHAR(40))
    MODIFIES SQL DATA
SELECT UTILISATEUR_ID, SURNOM, MAIL INTO AUTILISATEUR_ID, ASURNOM, AMAIL FROM UTILISATEURS WHERE (MAIL = AMAIL AND MDP = AMDP)$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_UTILISATEUR`(IN `ASURNOM` CHAR(40), IN `AMAIL` VARCHAR(255), IN `AMDP` VARCHAR(255))
    MODIFIES SQL DATA
INSERT INTO UTILISATEURS (
    SURNOM,
    MAIL,
    MDP)
    VALUES (
        ASURNOM,
        AMAIL,
        AMDP)$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_MESSAGE`(IN `AUTILISATEUR_ID` INT, IN `ATITRE` VARCHAR(80), IN `ATEXTE` TEXT)
    MODIFIES SQL DATA
INSERT INTO messages (
        UTILISATEUR_ID,
        TITRE,
        TEXTE)
        VALUES (
            AUTILISATEUR_ID,
            ATITRE,
            ATEXTE)$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UPDATE_MESSAGE`(IN `AMESSAGE_ID` INT, IN `ATITRE` VARCHAR(80), IN `ATEXTE` TEXT)
    MODIFIES SQL DATA
UPDATE MESSAGES SET
    TITRE = ATITRE,
    TEXTE = ATEXTE
WHERE MESSAGE_ID = AMESSAGE_ID$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `CONNEXION_UTILISATEUR`(IN `AMAIL` VARCHAR(255), IN `AMDP` VARCHAR(255), OUT `ISOK` INT)
    NO SQL
SELECT
    UTILISATEUR_ID
FROM utilisateurs
WHERE (MAIL = AMAIL AND MDP = AMDP)
LIMIT 1
INTO `ISOK`$$
DELIMITER ;
